source('utils.r')
source('random_forest_benchmark.r')
source('simple_regression.r')
source('constant.r')
source('kalman_filter.r')

Submit <- function(submit.type){
  time <- proc.time()
  print('Reading the data...')
  if(submit.type %in% c('RandomForestBenchmark', 'SimpleRegression', 'CurveKalmanFilter'))
    train <-read.csv( '../data/train.csv',  header = TRUE, na.strings = 'NA')
  else
    train <- NA
  test <-read.csv( '../data/test.csv',  header = TRUE, na.strings = 'NA')
  time <- RecordTime(time)

  print('Making predictions...')
  if(submit.type=='RandomForestBenchmark')
    predictions <- RandomForestBenchmark(train, test)
  else if(submit.type=='SimpleRegression')
    predictions <- SimpleRegression(train, test)
  else if(submit.type=='Constant')
    predictions <- Constant(test)
  else if(submit.type=='SimpleKalmanFilter')
    predictions <- KalmanFilter(train, test, simple=TRUE)
  else if(submit.type=='SimpleKalmanFilterSqrt')
    predictions <- KalmanFilter(train, test, simple=TRUE, timemap=sqrt)
  else if(submit.type=='SimpleKalmanFilterSquare')
    predictions <- KalmanFilter(train, test, simple=TRUE, timemap=function(x) return(x*x))
  else if(submit.type=='CurveKalmanFilter')
    predictions <- KalmanFilter(train, test, simple=FALSE)
  else stop('invalid submission type')
  time <- RecordTime(time)

  stopifnot(nrow(subset(predictions, is.na(trade_price))) == 0)
  print('Writing predictions to file...')
  submission.file.name <- paste('../predict/', submit.type, '.csv', sep='')
  write.csv(predictions, file = paste('../predict/', submission.file.name, sep=''), row.names = FALSE)
  time <- RecordTime(time)
}
